services:
  api:
    build: ./website/api
    container_name: api
    ports:
      - "8000:8000"
    restart: unless-stopped

  dashboard:
    build: ./website/dashboard
    container_name: dashboard
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
