stages:
  entrenar:
    wdir: model
    cmd: python train.py --data ../data/base-anuario-de-siniestralidad.xlsx --output-dir ../website/api
    deps:
      - train.py
      - ../data/base-anuario-de-siniestralidad.xlsx
