stages:
  entrenar:
    wdir: api
    cmd: python train_model.py --data base-anuario-de-siniestralidad.xlsx --output-dir .
    deps:
      - train_model.py
      - base-anuario-de-siniestralidad.xlsx
